Banned role and copy button
PythonFreeCourse/lms pull request #142
Opened 2020-09-08 14:37 UTC by orronai

2020-09-08 15:22 UTC, yammesicka requested changes

2020-09-08 15:22 UTC, yammesicka commented on lms/lmsweb/views.py
> +        request.endpoint not in ('login', 'logout')
I think checking if `current_user.is_authenticated and current.user.role.is_banned` might be more accurate

2020-09-08 15:22 UTC, yammesicka commented on lms/templates/banned.html
> +                המשתמש שלך מושהה עקב עבירה על תנאי הקורס.<br>
```
המשתמש שלך הושעה על ידי מנהל המערכת.
לפרטים נוספים אנא פנה אל צוות הניהול.
```

Generally I like the idea with the mailto, but I don't want the system to be specific for our course.
One of my next tasks is to to language localization and to remove the logo of our course ^^"

2020-09-08 15:22 UTC, yammesicka commented on lms/templates/navbar.html
> +      {%- if not current_user.role.is_banned %}
Why each section separately? Is this change really necessary?

2020-09-08 15:22 UTC, yammesicka commented on lms/templates/view.html
> +        <pre><code id="python-user-code" class="language-python line-numbers highlight">{{- current_file.code | trim(chars=' ') | e -}}</code></pre>
Let's try to remove this

2020-09-08 15:54 UTC, yammesicka requested changes

2020-09-08 15:54 UTC, yammesicka commented on lms/templates/view.html
> +        <button class="fa fa-copy" id="copy-button" title="Copy code" onclick="copy_code()" style="background-color:white;font-size:20px;"></button>
The style should be in the CSS, and the onclick should be in the JS file.

We try not to use inline CSS/JS.

2020-09-09 14:10 UTC, yammesicka requested changes

2020-09-09 14:10 UTC, yammesicka commented on lms/lmsweb/views.py
> +        request.path != '/login'
Is it really needed? We need to minimize the checks in `@before_request`, it is expensive.

2020-09-09 14:10 UTC, yammesicka commented on lms/static/my.css
> +	background-color:gray;
Fix the indentation

2020-09-09 14:10 UTC, yammesicka commented on lms/static/my.js
> +    var copyText = document.getElementById('python-user-code');
Use `let` or `const`, not `var`. Also, if possible, define the variables as soon as possible.

2020-09-09 14:42 UTC, yammesicka requested changes

2020-09-09 14:42 UTC, yammesicka commented on lms/templates/navbar.html
> +{% if request.path != '/login' and not current_user.role.is_banned %}
If we change it already, change it to current_user.is_authenticated

2020-09-09 14:42 UTC, yammesicka commented on lms/static/my.js
> +  copyCode(document.getElementById('copy-button'));
Follow the convention: change the name of the function to `trackCopyCodeButton`

2020-09-09 14:52 UTC, yammesicka requested changes

2020-09-09 14:52 UTC, yammesicka commented on lms/templates/navbar.html
> +{% if current_user.is_authenticated %}
and is not banned..

2020-09-09 14:59 UTC, orronai commented on lms/templates/navbar.html
> +{% if current_user.is_authenticated %}
My fault...

2020-09-09 15:16 UTC, yammesicka approved these changes
Cool, good job :)

2020-09-09 15:17 UTC, merged