PWA
PythonFreeCourse/lms pull request #199
Opened 2020-09-30 20:29 UTC by officialpm

# PWA Support for Python's Course LMS 🚀

 - [x] favicon.ico path fix 🔧
 - [x] Added Icons 🎨
 - [x] Added Manifest.json 🌐 -  Dynamic scope and start_url based on the configuration
 - [x] Added & Updated service worker to 5.1.2 workbox (sw.js) 👷
 - [x] Added routes - /manifest.json, /sw.js ➕

#### Solves issue #164 🤘🏻

2020-10-02 12:19 UTC, officialpm commented
@yammesicka @gal432 @orronai 
Please can you review this PR

2020-10-03 23:07 UTC, yammesicka requested changes

2020-10-03 23:07 UTC, yammesicka commented on lms/templates/base.html
> +    <meta name="apple-mobile-web-app-capable" content="yes">
This is lots of code for just a fallback, I think we should shrink it to be as slim as the W3C example [here](https://www.w3.org/TR/appmanifest/#using-a-link-element-to-link-to-a-manifest).

2020-10-03 23:08 UTC, yammesicka commented
Thanks for your great work! I've included some of my ideas in the comments. What do you think?

2020-10-04 09:19 UTC, officialpm commented
> Thanks for your great work! I've included some of my ideas in the comments. What do you think?

Yes I will work on them today!! 🤘🏻
It would be great if you include this in hacktoberfest!! Please?

2020-10-04 10:38 UTC, yammesicka commented
Sure, every issue merged in this repo is considered as a valid PR towards the Hacktoberfast :)

2020-10-04 12:19 UTC, yammesicka requested changes

2020-10-04 12:19 UTC, yammesicka commented on lms/lmsweb/views.py
> +        os.path.join(webapp.static_folder),
Please remove any unnecessary joins :)

2020-10-04 12:19 UTC, yammesicka commented on lms/templates/base.html
> +    <link rel="icon" sizes="16x16 32x32 48x48"  href="{{ url_for('static', filename = 'icons/icons.ico')}}">
In Python we don't put spaces before and after the equal sign. Please trim them :)

2020-10-04 12:19 UTC, yammesicka commented
An excellent job! Just more few simple cleanups to go :)

2020-10-04 12:44 UTC, yammesicka requested changes

2020-10-04 12:44 UTC, yammesicka commented on lms/lmsweb/views.py
> +from flask import (jsonify, make_response, render_template, request,
Please keep our sorting conventions in regards to `import`s.

It should be organized from a to z, and split into 3 blocks: standard modules,  3rd party modules and our modules.

2020-10-04 12:44 UTC, yammesicka commented on lms/templates/base.html
> +    <link rel="icon" sizes="16x16 32x32 48x48"  href="{{ url_for('static', filename='icons/icons.ico')}}">
Put a space before the `}}` (in this line, and in the line after).

2020-10-05 10:49 UTC, yammesicka requested changes

2020-10-05 10:49 UTC, yammesicka commented on lms/lmsweb/views.py
> +from lms.lmsweb.manifest import MANIFEST
This import line should appear after `from lms.lmsweb.config import LANGUAGES, LOCALE`

2020-10-05 10:57 UTC, yammesicka approved these changes
Great job! :+1:

2020-10-05 10:59 UTC, officialpm commented
> Great job! 👍

Thankyou 💯

2020-10-05 11:03 UTC, merged