Fix Bug Preventing Reupload
PythonFreeCourse/lms pull request #229
Opened 2020-10-06 09:27 UTC by itamargran

Compare the content of a re-uploded solution only with the user's latest uploaded solution of that specific exercise.

2020-10-06 10:57 UTC, orronai commented on lms/tests/test_solutions.py
> +            already_hashed=True,
You can write these two lines in one line.

2020-10-06 10:58 UTC, orronai commented
Looks good!

2020-10-07 18:27 UTC, yammesicka requested changes

2020-10-07 18:27 UTC, yammesicka commented on lms/lmsdb/models.py
> +
Try not to add new lines after the function header

2020-10-08 20:51 UTC, yammesicka approved these changes

2020-10-08 20:52 UTC, merged