Contribution guidelines
PythonFreeCourse/lms pull request #239
Opened 2020-10-09 12:01 UTC by ron-huberfeld

docs: add contribution convention section

2020-10-09 13:35 UTC, ron-huberfeld commented
@yammesicka I'll move this section to a separate `CONTRIBUTING.md` file.
Do you have any preferences to the file structure?

2020-10-10 04:15 UTC, yammesicka requested changes

2020-10-10 04:15 UTC, yammesicka commented on CONTRIBUTING.md
> +Follow the [commit messages specification](https://www.conventionalcommits.org/en/v1.0.0/)
Add dot in the end of the sentence.

2020-10-10 04:15 UTC, yammesicka commented on CONTRIBUTING.md
> +2. Create a new branch (git checkout -b 'branch name')
Use ` before and after the git command.

2020-10-10 04:15 UTC, yammesicka commented on CONTRIBUTING.md
> +Please note we have a code of conduct, please follow it in all your interactions with the project.
Link to it :)

2020-10-10 23:55 UTC, yammesicka requested changes

2020-10-10 23:55 UTC, yammesicka commented on README.md
> +View [contributing guidelines](https://github.com/PythonFreeCourse/lms/blob/master/CONTRIBUING.md)
`.` at the end of the sentence

2020-10-11 05:13 UTC, merged