Fix svg bug
PythonFreeCourse/lms pull request #264
Opened 2020-10-27 22:41 UTC by ron-huberfeld

- [v] Modify ref link to hawcons-filled.css
- [v] Modify icons usage in html

2020-10-27 22:45 UTC, yammesicka commented
I'm probably missing something. How does this PR resolves the bug?

The problem is that currently you can't see SVG images that the user uploaded :)

2020-10-29 08:45 UTC, ron-huberfeld commented
> I'm probably missing something. How does this PR resolves the bug?
> 
> The problem is that currently you can't see SVG images that the user uploaded :)

I'll revert it and try again.

2020-10-30 15:33 UTC, yammesicka requested changes

2020-10-30 23:28 UTC, yammesicka requested changes

2020-10-30 23:28 UTC, yammesicka commented on lms/templates/view.html
> +        <pre><code id="user-code" class="language-{{ current_file | language_name }} line-numbers highlight">{% if current_file | language_name in image_extensions %}<div class="code-image-block">{%
Please create a dictionary in utils.files to manage the mimetype; currently it's only semi-generic (for `.jpg`, for example, the mimetype is `img/jpeg` and not `img/jpg`, for `.ico` it's `x-icon` and so on). You can use [`mimetype.guess_type`](https://docs.python.org/3/library/mimetypes.html#mimetypes.guess_type).

2020-10-31 14:13 UTC, merged